name: Events demo 1
on:
#    push:
#        branches:
#            - "main"
    pull_request:
        types: 
            - opened
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Outpu event data
              run: echo "${{ toJson(github.event)}}"
            - name: Get code
              uses: actions/checkout@v4
            - name: Setup environment
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test
            - name: Build code
              run: npm run build
            - name: Deploy project 
              run: echo "Deploying..."